name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      extra_plugin_runners: 'moodle-plugin-ci add-plugin sarahjcotton/moodle-local_aws'
      disable_grunt: true
